#NAME: Bryan Luo
#EMAIL: luobryan@ucla.edu
#ID: 605303956

dist: 
	tar -cvzf lab4a-605303956.tar.gz Makefile README build_run.png connected.png copy.png git.png my_beaglebone.jpg

clean:
	rm -f *.tar.gz 