#NAME: Bryan Luo
#EMAIL: luobryan@ucla.edu
#ID: 605303956
default: lab1a
lab1a: lab1a.c
	gcc lab1a.c -o lab1a -Wall -Wextra
clean:
	rm -f *.o *.gz lab1a
dist:
	tar -zcvf lab1a-605303956.tar.gz lab1a.c Makefile README
