#NAME: Bryan Luo
#EMAIL: luobryan@ucla.edu
#ID: 605303956

default: 
	rm -f lab3b
	ln run_lab_script.sh lab3b
	chmod 777 lab3b
dist: default
	tar -cvzf lab3b-605303956.tar.gz lab3b.py Makefile README run_lab_script.sh
clean:
	rm -f *.tar.gz lab3b
