#NAME: Bryan Luo
#EMAIL: luobryan@ucla.edu
#ID: 605303956

build:
	gcc -Wall -Wextra -o lab3a  lab3a.c
dist: build
	tar -cvzf lab3a-605303956.tar.gz lab3a.c ext2_fs.h README Makefile
clean:
	rm -f lab3a-605303956.tar.gz lab3a

